package com.smartswitch.utils.enums

enum class TransferState {
    INITIAL_STATE,
    STARTING_TRANSFER_STATE,
    TRANSFERRING_STATE,
    TRANSFER_COMPLETE_STATE,
    TRANSFER_FAILED_STATE,
    TRANSFER_ASK_RECEIVER_STATE,
    CONNECTION_TIMEOUT_STATE,
    TRANSFER_CANCELLED_STATE
}